version: "3.0"
services:

  app:
    container_name: "app"
    image: app
    env_file:
      - .env
    build:
      context: .
      dockerfile: DOCKERFILE
    links:
      - api
    command: python telegram/telegram_test.py
    networks:
      - net


  api:
    container_name: "api"
    image: api
    env_file:
      - .env
    build:
      context: .
      dockerfile: DOCKERFILE
    links:
      - db
    command: sh -c "python -m alembic upgrade head && python main.py"
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - net


  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - net
  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_test
    ports:
      - "5433:5432"
    networks:
      - net
networks:
  net:
    driver: bridge