version: "3.0"
services:

  app:
    container_name: "app"
    image: app
    env_file:
      - .env
    build:
      context: .
      dockerfile: DOCKERFILE
    links:
      - api
    command: python telegram/telegram_test.py
    networks:
      - net


  api:
    container_name: "api"
    image: api
    env_file:
      - .env
    build:
      context: .
      dockerfile: DOCKERFILE
    links:
      - db
    command: python main.py
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - net


  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - net
#  db_migration:
#    image: app
#    restart: "on-failure"
#    links:
#      - db
#    depends_on:
#      - db
#    command: sh -c "python -m alembic upgrade head"
networks:
  net:
    driver: bridge